redis: &redis
  port: 6379
  db: 15

development: &development
  # namespace: iot_thermostat
  <<: *redis
  host: localhost

production:
  # namespace: iot_thermostat
  <<: *redis
  host: localhost

test:
  # namespace: iot_thermostat
  <<: *redis
  host: localhost